#!/bin/bash
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=8
#SBATCH --time=1:30:00
#SBATCH --mem=10GB
#SBATCH --account=fehder_718

module load gcc/8.3.0
module load python
module load stata

export PYTHONPATH=/project/fehder_718/python/pkgs:${PYTHONPATH}
export TMPDIR=/project/fehder_718/frt_2021b_data/


# run the stata file to make the cross walk
stata-mp -b do mk_cross_zip2cbsa.do

# make the region files
python3 proc-2-regional-exec.py

